const redisPages = [
  // index
  '/',
  '/bridal',
  '/all/sale',
  /* list top up 400pv */
  /* 7  分类使用正则匹配 */
  // '/all/plus-size-bridesmaid-dresses',
  // '/all/plus-size-bridesmaid-dresses?sort_by=popularity',
  // '/all/bridesmaid-dresses',
  // '/all/bridesmaid-dresses?sort_by=popularity',
  // '/all/bridesmaid-dresses?sort_by=popularity&page=1',
  // '/all/bridesmaid-dresses?fixedBrandId=16',
  // '/all/bridesmaid-dresses?fixedBrandId=20',
  // '/all/bridesmaid-dresses?sort_by=new-arrival',
  // '/all/bridesmaid-dresses/colors/dusty-sage',
  // '/all/bridesmaid-dresses/colors/eucalyptus',
  // '/all/bridesmaid-dresses/colors/dusty-blue',
  // '/all/bridesmaid-dresses/colors/black',
  // '/all/bridesmaid-dresses/colors/dusty-rose',
  // '/all/bridesmaid-dresses/colors/champagne',
  // '/all/bridesmaid-dresses/colors/paprika',
  // '/all/bridesmaid-dresses/colors/terracotta',
  // '/all/bridesmaid-dresses/colors/dark-green',
  // '/all/bridesmaid-dresses/colors/blushing-pink',
  // '/all/bridesmaid-dresses/colors/pine',
  // '/all/bridesmaid-dresses/colors/burgundy',
  // '/all/bridesmaid-dresses/colors/dark-navy',
  // '/all/bridesmaid-dresses/colors/agave',
  // '/all/bridesmaid-dresses/colors/sky-blue',
  // '/all/bridesmaid-dresses/with/length/floor-length',
  // '/all/bridesmaid-dresses/with/fabric/chiffon',
  // '/all/bridesmaid-dresses/colors/bronzer',
  // '/all/bridesmaid-dresses/colors/eucalyptus?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/dusty-sage?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/cabernet',
  // '/all/bridesmaid-dresses/colors/lilac',
  // '/all/bridesmaid-dresses/colors/rust',
  // '/all/bridesmaid-dresses/colors/cedar-rose',
  // '/all/bridesmaid-dresses/colors/dusty-blue?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/eucalyptus/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/terracotta/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/champagne-rose',
  // '/all/bridesmaid-dresses/colors/taupe',
  // '/all/bridesmaid-dresses/colors/wisteria',
  // '/all/bridesmaid-dresses/with/length/floor-length,ankle-length',
  // '/all/bridesmaid-dresses/colors/olive',
  // '/all/bridesmaid-dresses/colors/bermuda',
  // '/all/bridesmaid-dresses/colors/steel-blue',
  // '/all/bridesmaid-dresses/colors/red',
  // '/all/bridesmaid-dresses/colors/white-alabaster',
  // '/all/bridesmaid-dresses/colors/black/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/desert-rose',
  // '/all/bridesmaid-dresses/colors/dusty-rose?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/peacock',
  // '/all/bridesmaid-dresses/colors/black?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/plum',
  // '/all/bridesmaid-dresses/colors/mist',
  // '/all/bridesmaid-dresses/colors/vintage-mauve',
  // '/all/bridesmaid-dresses/colors/mai-tai',
  // '/all/bridesmaid-dresses/colors/dusty-blue/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/eucalyptus/with/fabric/chiffon',
  // '/all/bridesmaid-dresses/colors/twilight',
  // '/all/bridesmaid-dresses/colors/rose-petal',
  // '/all/bridesmaid-dresses/colors/cedar-rose/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/blushing-pink?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/ink-blue',
  // '/all/bridesmaid-dresses/colors/terracotta?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/amethyst',
  // '/all/bridesmaid-dresses/colors-family/green/colors/eucalyptus',
  // '/all/bridesmaid-dresses/colors-family/green/colors/dusty-sage',
  // '/all/bridesmaid-dresses/colors/white-alabaster/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/royal-blue',
  // '/all/bridesmaid-dresses/with/fabric/velvet',
  // '/all/bridesmaid-dresses/colors/paprika?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/pine?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/white',
  // '/all/bridesmaid-dresses/colors/pomegranate',
  // '/all/bridesmaid-dresses/colors/burgundy?sort_by=popularity',
  // '/all/bridesmaid-dresses/colors/agave/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/pine/with/fabric/stretch-satin',
  // '/all/bridesmaid-dresses/colors/english-rose',
  // '/all/bridesmaid-dresses/colors/matcha',
  // '/all/bridesmaid-dresses/colors-family/azazie-2023-new-color',
  // '/all/bridesmaid-dresses/colors-family/2023bdfallcolors?sort_by=new_arrival&page=1',
  // '/all/bridesmaid-dresses/colors-family/green',
  // '/all/bridesmaid-dresses/colors/juniper',
  // '/all/bridesmaid-dresses/colors-family/blue',
  // '/all/bridesmaid-dresses/colors/moody-blue',
  // '/all/bridesmaid-dresses?sort_by=new_arrival',
  // '/all/bridesmaid-dresses/colors/dusty-blue?sort_by=new_arrival&page=1',
  // '/all/bridesmaid-dresses/colors/dusty-blue/with/fabric/chiffon',
  // '/all/bridesmaid-dresses/colors/black?sort_by=new_arrival&page=1',
  // '/all/bridesmaid-dresses/colors-family/2023bdfallcolors',
  // '/all/bridesmaid-dresses/colors/dusty-sage?sort_by=new_arrival&page=1',
  // '/all/bridesmaid-dresses/with/length/floor-length?sort_by=new_arrival',
  // '/all/bridesmaid-dresses/with/fabric/stretch-satin?sort_by=new_arrival',
  // '/all/bridesmaid-dresses/with/fabric/chiffon?sort_by=new_arrival',
  // '/all/bridesmaid-dresses/colors-family/black',
  // '/all/bridesmaid-dresses/colors/champagne?sort_by=new_arrival&page=1',
  // '/all/bridesmaid-dresses/colors/sunset',
  // '/all/bridesmaid-dresses/colors/pearl-pink',
  // '/all/bridesmaid-dresses/colors/sand',
  // '/all/bridesmaid-dresses/with/price/price79-100',
  // '/all/bridesmaid-dresses/colors-family/orange',
  // '/all/bridesmaid-dresses/colors-family/2024-spring-colors',
  // '/all/bridesmaid-dresses/with/brand/barbie-azazie',
  // '/all/bridesmaid-dresses/with/length/knee-length',
  // '/all/bridesmaid-dresses/with/price/price79-100?sort_by=price_asc&page=1',
  // '/all/bridesmaid-dresses/colors-family/pink',
  /* 7 end */
  /* 2 */
  // '/all/wedding-dresses',
  // '/all/wedding-dresses/with/price/price0-400',
  // '/all/wedding-dresses/plus-size',
  // '/all/wedding-dresses/with/silhouette/a-line',
  // '/all/wedding-dresses?sort_by=new-arrival',
  // '/all/wedding-dresses/with/collection/modern-sleek',
  // '/all/wedding-dresses/with/collection/fairy-tale',
  // '/all/wedding-dresses/with/collection/sexy-glam',
  // '/all/wedding-dresses?sort_by=top_rated&page=1',
  // '/all/wedding-dresses/with/trending/rehearsal?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses/with/silhouette/trumpet-mermaid',
  // '/all/wedding-dresses/with/trending/bridal-shower?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses/with/trending/rehearsal?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses/with/trending/engagement?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses/with/trending/bridal-shower?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses/with/trending/bachelorette?sort_by=new_arrival&page=1',
  // '/all/wedding-dresses?fixedBrandId=20',
  // '/all/wedding-dresses/with/brand/barbie-azazie',
  '/all/cheap-wedding-dresses',
  '/wedding-themes/spring-wedding',
  '/wedding-themes/beach-wedding',
  '/all/plus-size-mother-of-the-bride-dresses',

  /* 2 end */
  /* 5 */
  '/all/accessories',
  '/all/accessories?sort_by=popularity',
  '/all/women-accessories',
  '/all/women-accessories?sort_by=top_rated&page=1',
  /* 5 end */
  /* 6 */
  '/all/wedding-veils',
  '/all/wedding-veils?sort_by=popularity',
  /* 6 end */
  /* 8  */
  // '/all/mother-of-the-bride-dresses',
  // '/all/mother-of-the-bride-dresses?sort_by=popularity',
  // '/all/mother-of-the-bride-dresses/with/length/floor-length',
  // '/all/mother-of-the-bride-dresses?sort_by=new-arrival',
  // '/all/mother-of-the-bride-dresses?sort_by=popularity',
  // '/all/mother-of-the-bride-dresses/colors/dark-navy',
  // '/all/mother-of-the-bride-dresses/colors/champagne',
  // '/all/mother-of-the-bride-dresses/with/price/price0-150',
  // '/all/mother-of-the-bride-dresses?sort_by=top_rated&page=1',
  // '/all/mother-of-the-bride-dresses/colors/dusty-sage',
  // '/all/mother-of-the-bride-dresses/colors/dusty-rose',
  // '/all/mother-of-the-bride-dresses/colors/black',
  // '/all/mother-of-the-bride-dresses/with/length/tea-length',
  // '/all/mother-of-the-bride-dresses/with/length/knee-length',
  // '/all/mother-of-the-bride-dresses/with/brand/upstudio',
  // '/all/mother-of-the-bride-dresses/with/silhouette/a-line-princess',
  '/all/plus-size-mother-of-the-bride-dress',
  '/all/plus-size-mother-of-the-bride-dresses?sort_by=popularity',
  /* 8 end */
  /* 9 */
  '/all/junior-bridesmaid-dresses',
  '/all/junior-bridesmaid-dresses?sort_by=popularity',
  '/all/junior-bridesmaid-dresses?sort_by=popularity&page=1',
  '/all/junior-bridesmaid-dresses/colors/terracotta?sort_by=top_rated&page=1',
  '/all/junior-bridesmaid-dresses/with/length/floor-length',
  '/all/junior-bridesmaid-dresses/colors/eucalyptus',
  '/all/junior-bridesmaid-dresses?sort_by=new_arrival',
  '/all/junior-bridesmaid-dresses/colors/dusty-blue',
  // jbd 大类
  '/all/all-junior',
  '/all/all-junior/colors-family/azazie-2023-new-color',
  '/all/all-junior/with/length/ankle-length',
  '/all/all-junior/colors/dusty-sage',
  '/all/all-junior?sort_by=popularity&page=1',
  '/all/all-junior/with/length/knee-length,tea-length,mini',
  '/all/all-junior/colors/dusty-rose',
  '/all/all-junior/with/fabric/matte-satin',
  '/all/all-junior/colors/eucalyptus',
  '/all/all-junior/colors/dusty-blue',
  '/all/all-junior?sort_by=price_asc',
  '/all/all-junior/with/length/floor-length',
  /* 9 end */
  /* 10 */
  '/all/flower-girl-dresses',
  '/all/flower-girl-dresses?sort_by=popularity',
  '/all/flower-girl-dresses/with/length/ankle-length',
  /* 10 end */
  /* 13 */
  '/all/wraps',
  '/all/wraps?sort_by=popularity',
  /* 13 end */
  /* 15 */
  '/all/sashes',
  '/all/sashes?sort_by=popularity',
  /* 15 end */
  '/all/separates',
  '/all/separates?sort_by=popularity',
  /** 33  */
  // '/swatches-fabric',
  // '/swatches',
  // '/all/swatches/colors/dusty-sage',
  /* 36 */
  '/all/fabrics',
  '/all/fabrics?sort_by=popularity',
  /* 45 */
  '/all/maternity-bridesmaid-dresses',
  '/all/maternity-bridesmaid-dresses?sort_by=popularity',
  /* 45 end */
  /* 129 */
  '/all/gifts?sort_by=popularity',
  /* 138 */
  '/all/groomsmen-accessories',
  '/all/groomsmen-accessories/with/accessory-type/bow-tie,skinny-tie,wide-tie',
  '/all/groomsmen-accessories/with/accessory-type/vest,suspenders',
  /* 138 end */
  /* 158 */
  '/all/modest-bridesmaid-dresses',
  '/all/modest-bridesmaid-dresses?sort_by=popularity',
  /* 158 end */
  /* 1508 */
  '/all/garment-bags',
  /* 3076 */
  '/all/jewelry',
  '/all/jewelry?sort_by=popularity',
  /* 3076  end */
  /* 3077 */
  '/all/headpieces',
  '/all/headpieces?sort_by=popularity',
  /* 3077 end */
  /* 3099 */
  '/all/shapewear',
  '/all/shapewear?sort_by=popularity',
  /* 3099  end */
  /* 3101 */
  '/all/all-gifts',
  /* 3102 */
  '/all/shoes',
  '/all/shoes?sort_by=popularity',
  '/all/shoes/with/occasion/bridal-party',
  /* 3108 */
  '/all/azazie-digital-gift-cards',
  /* 3109 */
  '/all/bags',
  /* 3109 end */
  /* ready to ship */
  '/all/ready-to-ship?current_in_stock=yes',
  '/all/ready-to-ship-maternity?current_in_stock=yes',
  '/all/ready-to-ship-modest?current_in_stock=yes',
  '/all/ready-to-ship-formal?current_in_stock=yes',
  '/all/ready-to-ship/with/discount/7?current_in_stock=yes',
  '/all/ready-to-ship/with/discount/7?current_in_stock=yes&sort_by=new_arrival&page=1',
  '/all/ready-to-ship-mother-of-the-brides?current_in_stock=yes', // cat 8
  '/all/ready-to-ship-bridesmaids/with/discount/7?current_in_stock=yes', // cat 7
  '/all/ready-to-ship-bridesmaids?current_in_stock=yes', // cat 7
  '/all/ready-to-ship-brides?current_in_stock=yes', // cat 2
  '/all/ready-to-ship/with/discount/5?current_in_stock=yes',
  /* ready to ship end */
  /* sample */
  '/sample-dresses/how-it-works',
  '/all/sample-brides?current_in_stock=yes',
  '/all/sample-maternity?current_in_stock=yes',
  '/all/sample-modest?current_in_stock=yes',
  '/all/sample-dresses',
  '/all/sample-dresses?current_in_stock=yes',
  '/all/sample-bridesmaids', // cat 7
  '/all/sample-bridesmaids?current_in_stock=yes', // cat 7
  '/all/sample-bridesmaids?sort_by=popularity&current_in_stock=yes', // cat 7
  '/all/sample-bridesmaids/with/fabric/stretch-satin?current_in_stock=yes',
  '/all/sample-bridesmaids/colors/dusty-blue?current_in_stock=yes',
  '/all/sample-mother-of-the-bride?current_in_stock=yes', // cat 8
  '/all/sample-junior-bridesmaid-dresses?sort_by=popularity&current_in_stock=yes', // cat 9
  '/all/sample-mother-of-the-bride',
  '/all/sample-bridesmaids/with/fabric/chiffon',
  '/all/sample-bridesmaids/with/fabric/stretch-satin',
  '/all/sample-brides?sort_by=popularity&current_in_stock=yes',
  '/all/sample-bridesmaids/with/length/floor-length',
  '/all/sample-junior-bridesmaid-dresses?sort_by=popularity&current_in_stock=yes',
  '/all/sample-mother-of-the-bride/with/length/floor-length',
  '/all/sample-mother-of-the-bride?sort_by=popularity&current_in_stock=yes',
  '/all/sample-brides',
  '/all/sample-bridesmaids/with/fabric/stretch-chiffon',
  /* sample end */
  '/all/last-chance-outlet?current_in_stock=yes',
  /** rts */
  '/all/final-sale',
  '/all/final-sale/with/category/ready-to-ship-bridesmaids?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale?current_in_stock=yes',
  '/all/final-sale?current_in_stock=yes&mid=1052918,1052906,1056565,1052922,1056542,1052860,1052928,1052929,1056544',
  '/all/final-sale/with/category/special-offer-special-occasion-dresses',
  '/all/final-sale/with/category/ready-to-ship-brides?current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-brides?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-bridesmaids/brand/azazie-x-kendall-kylie?current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-mother-of-the-brides?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-special-occasion-dresses?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-special-occasion-dresses?sort_by=popularity',
  '/all/final-sale/with/category/ready-to-ship-mother-of-the-brides?current_in_stock=yes',
  '/all/final-sale/with/discount/7?current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-jewelry?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-shoes?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale-acc-on-sale',
  '/all/final-sale/with/category/ready-to-ship-junior-bridesmaid-dresses?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-flower-girl-dresses?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale?current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-shapewear?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-headpieces?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-groomsmen-accessories?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/discount/1.5',
  '/all/final-sale/with/category/special-offer-wraps?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-brides?current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-bridesmaids',
  '/all/final-sale/with/category/ready-to-ship-bridesmaids/brand/azazie-x-kendall-kylie?current_in_stock=yes',
  '/all/final-sale/with/category/ready-to-ship-bridesmaids?current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-wedding-veils?sort_by=popularity&current_in_stock=yes',
  '/all/final-sale/with/category/special-offer-special-occasion-dresses',
  // 其他页面
  '/promotion'
]

// 时装列表缓存页面
const redisListSod = [
  /* 3 */
  '/all/special-occasion-dresses',
  '/all/guest-of-wedding-dresses',
  '/all/prom-dresses',
  '/all/formal-dresses',
  '/all/guest-of-wedding-dresses/with/season/spring',
  '/all/guest-of-wedding-dresses/with/occasion/formal',
  '/all/special-occasion-dresses/with/season/spring',
  '/all/special-occasion-dresses?fixedBrandId=16',
  '/all/cocktail-dresses',
  '/all/guest-of-wedding-dresses/with/occasion/vacation',
  '/all/special-occasion-dresses/colors-family/white',
  '/all/special-occasion-dresses/with/size/1x,2x,3x',
  '/all/graduation-dresses',
  '/all/guest-of-wedding-dresses/with/season/summer',
  '/all/special-occasion-dresses?sort_by=new_arrival&page=1',
  '/all/guest-of-wedding-dresses/with/season/fall',
  '/all/special-occasion-dresses/with/fabric/sequins',
  '/all/semi-formal-dresses',
  '/all/homecoming-dresses',
  '/all/guest-of-wedding-dresses/with/season/winter',
  '/all/guest-of-wedding-dresses/ith/occasion/black-tie',
  '/all/guest-of-wedding-dresses/with/price/price0-50',
  '/all/special-occasion-dresses/with/length/midi',
  /* 3 end */
  // '/all/atelier', // 这是个落地页 不是列表
  // '/all/atelier-dresses',
  // '/all/atelier-party-dresses',
  // '/all/atelier-cocktail-dresses',
  // '/all/atelier-formal-dresses',
  // '/all/atelier-guest-of-wedding-dresses',
  // '/all/atelier-gala-dresses',
  // '/all/atelier-special-event-dresses',
  // '/all/atelier-formal-dresses/with/shop-by-category/dresses',
  // '/all/atelier-formal-dresses/with/shop-by-category/gowns',
  /** 3110 */
  '/all/black-tie-dresses'
]

//  detail top 700
const detailPages = [
  '/products/anniston-dusty-sage-halter-neck-tiered-midi-sod-dress/222090',
  '/products/azazie-aaliyah-modest-bridesmaid-dresses',
  '/products/azazie-adelyn-dark-green-a-line-lace-chiffon-floor-length-bridesmaid-dress/157831',
  '/products/azazie-adina-black-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146643',
  '/products/azazie-adina-black-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146643?is_plus_size=1',
  '/products/azazie-adina-dark-navy-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146641',
  '/products/azazie-adina-dusty-blue-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146642',
  '/products/azazie-adina-dusty-blue-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146642?is_plus_size=1',
  '/products/azazie-adina-vintage-mauve-a-line-boatneck-sequins-chiffon-floor-length-mother-of-the-bride-dress/146648',
  '/products/azazie-aerith-diamond-white-sheath-bow-stretch-crepe-chapel-train-wedding-dress/146601',
  '/products/azazie-airellie-diamond-white-champagne-a-line-off-the-shoulder-tulle-chapel-train-wedding-dress/228881',
  '/products/azazie-alani-dusty-sage-a-line-square-neckline-chiffon-floor-length-bridesmaid-dress/232558',
  '/products/azazie-alani-eucalyptus-a-line-square-neckline-chiffon-floor-length-bridesmaid-dress/232559',
  '/products/azazie-alia-black-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190791',
  '/products/azazie-alia-dusty-blue-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190805',
  '/products/azazie-alia-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190808',
  '/products/azazie-alia-eucalyptus-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190809',
  '/products/azazie-alia-matcha-a-line-pleated-chiffon-floor-length-bridesmaid-dress/220853',
  '/products/azazie-alia-mist-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190821',
  '/products/azazie-alia-pine-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190833',
  '/products/azazie-aliana-diamond-white-nude-mermaid-lace-tulle-chapel-train-wedding-dress/221845',
  '/products/azazie-alisondra-black-sheath-scoop-lace-lace-floor-length-mother-of-the-bride-dress/205561',
  '/products/azazie-alisondra-champagne-sheath-scoop-lace-lace-floor-length-mother-of-the-bride-dress/205565',
  '/products/azazie-alisondra-dark-navy-sheath-scoop-lace-lace-floor-length-mother-of-the-bride-dress/205567',
  '/products/azazie-allessia-maternity-bridesmaid-dress',
  '/products/azazie-almendra-lavender-a-line-sweetheart-neckline-mesh-floor-length-bridesmaid-dress/191657',
  '/products/azazie-amaria-diamond-white-blushing-pink-ball-gown-sequins-tulle-chapel-train-wedding-dress/225235',
  '/products/azazie-amethyst-dusty-rose-a-line-v-neck-sequins-chiffon-floor-length-mother-of-the-bride-dress/110664',
  '/products/azazie-amila-diamond-white-a-line-v-neck-lace-chiffon-knee-length-wedding-dress/214049',
  '/products/azazie-amya-diamond-white-a-line-pleated-tulle-ankle-length-flower-girl-dress/196082',
  '/products/azazie-amyra-black-sheath-off-the-shoulder-stretch-satin-floor-length-bridesmaid-dress/228354',
  '/products/azazie-amyra-eucalyptus-sheath-off-the-shoulder-stretch-satin-floor-length-bridesmaid-dress',
  '/products/azazie-amyra-pine-sheath-off-the-shoulder-stretch-satin-floor-length-bridesmaid-dress/228369',
  '/products/azazie-anadia-diamond-white-champagne-a-line-v-neck-tulle-chapel-train-wedding-dress/221839',
  '/products/azazie-annabelle-maternity-bridesmaid-dress',
  '/products/azazie-anne-stormy-sheath-sweetheart-sequins-lace-asymmetrical-mother-of-the-bride-dress/168623',
  '/products/azazie-anne-taupe-sheath-sweetheart-sequins-lace-asymmetrical-mother-of-the-bride-dress/141136',
  '/products/azazie-annetta-black-a-line-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/222242',
  '/products/azazie-annetta-dark-green-a-line-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/222246',
  '/products/azazie-annetta-dark-navy-a-line-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/222247',
  '/products/azazie-annette-dusty-rose-a-line-lace-chiffon-floor-length-mother-of-the-bride-dress/163504',
  '/products/azazie-antheia-diamond-white-mermaid-sequins-stretch-crepe-chapel-train-wedding-dress/106865',
  '/products/azazie-aqua-cabernet-a-line-v-neck-pleated-stretch-satin-floor-length-bridesmaid-dress/194248',
  '/products/azazie-arabelle-diamond-white-a-line-v-neck-lace-tulle-cathedral-train-wedding-dress/204437',
  '/products/azazie-aracely-diamond-white-mermaid-off-the-shoulder-stretch-crepe-chapel-train-wedding-dress/225136',
  '/products/azazie-ardea-diamond-white-a-line-v-neck-pleated-stretch-crepe-knee-length-wedding-dress/211306',
  '/products/azazie-arianthe-wisteria-a-line-matte-satin-floor-length-junior-bridesmaid-dress-with-pockets/186884',
  '/products/azazie-ariya-diamond-white-a-line-lace-tulle-chapel-train-wedding-dress/168650',
  '/products/azazie-arlette-diamond-white-nude-mermaid-sweetheart-sequins-tulle-chapel-train-wedding-dress/225221',
  '/products/azazie-armadan-diamond-white-champagne-a-line-sequins-tulle-cathedral-train-wedding-dress/188140',
  '/products/azazie-aruba-dusty-blue-a-line-pleated-viscose-floor-length-bridesmaid-dress/199491',
  '/products/azazie-ashana-dusty-sage-sheath-sweetheart-lace-mesh-floor-length-bridesmaid-dress/206834',
  '/products/azazie-ashana-sky-blue-sheath-sweetheart-lace-mesh-floor-length-bridesmaid-dress/206852',
  '/products/azazie-august-diamond-white-nude-a-line-lace-sweep-train-wedding-dress/196168',
  '/products/azazie-aurelie-diamond-white-mermaid-off-the-shoulder-stretch-satin-chapel-train-wedding-dress/201620',
  '/products/azazie-aurorie-diamond-white-champagne-a-line-sequins-tulle-chapel-train-wedding-dress/227585',
  '/products/azazie-austyn-diamond-white-ball-gown-lace-tulle-knee-length-flower-girl-dress/106208',
  '/products/azazie-ava-diamond-white-a-line-off-the-shoulder-stretch-chiffon-floor-length-wedding-dress/211297',
  '/products/azazie-avelina-champagne-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145941',
  '/products/azazie-avelina-dusty-blue-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145948',
  '/products/azazie-avelina-dusty-sage-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145950',
  '/products/azazie-avelina-eucalyptus-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/188353',
  '/products/azazie-avelina-paprika-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145974',
  '/products/azazie-avelina-steel-blue-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145992',
  '/products/azazie-aziza-wisteria-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/200563',
  '/products/azazie-azul-diamond-white-a-line-sweetheart-lace-tulle-tea-length-wedding-dress/223399',
  '/products/azazie-bai-diamond-white-mermaid-scoop-sequins-stretch-crepe-cathedral-train-wedding-dress/146806',
  '/products/azazie-bailora-black-mermaid-ruched-chiffon-floor-length-mother-of-the-bride-dress/228769',
  '/products/azazie-becca-bridesmaid-dress',
  '/products/azazie-becca-dusty-blue-sheath-v-neck-chiffon-floor-length-bridesmaid-dress/206695',
  '/products/azazie-becca-dusty-sage-sheath-v-neck-chiffon-floor-length-bridesmaid-dress/206698',
  '/products/azazie-becca-eucalyptus-sheath-v-neck-chiffon-floor-length-bridesmaid-dress/206699',
  '/products/azazie-becca-sky-blue-sheath-v-neck-chiffon-floor-length-bridesmaid-dress/206728',
  '/products/azazie-belladonna-black-mermaid-scoop-pleated-mesh-floor-length-mother-of-the-bride-dress/170495',
  '/products/azazie-belladonna-champagne-mermaid-scoop-pleated-mesh-floor-length-mother-of-the-bride-dress/170491',
  '/products/azazie-belladonna-mother-of-the-bride-dress',
  '/products/azazie-belladonna-wisteria-mermaid-scoop-pleated-mesh-floor-length-mother-of-the-bride-dress/170451',
  '/products/azazie-bellisima-diamond-white-champagne-a-line-v-neck-tulle-chapel-train-wedding-dress/183437',
  '/products/azazie-bellona-black-sheath-boatneck-luxe-knit-ballerina-length-mother-of-the-bride-dress/206941',
  '/products/azazie-beryl-agave-sheath-luxe-knit-floor-length-bridesmaid-dress/222194',
  '/products/azazie-beryl-dusty-rose-sheath-luxe-knit-floor-length-bridesmaid-dress/222200',
  '/products/azazie-beth-stormy-a-line-scoop-sequins-chiffon-knee-length-mother-of-the-bride-dress/205601',
  '/products/azazie-bettina-dark-navy-a-line-lace-chiffon-floor-length-mother-of-the-bride-dress/152090',
  '/products/azazie-birdie-vintage-mauve-a-line-queen-anne-sequins-chiffon-floor-length-mother-of-the-bride-dress/116692',
  '/products/azazie-bo-peep-eucalyptus-a-line-bow-matte-satin-knee-length-flower-girl-dress/199409',
  '/products/azazie-bondi-agave-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213183',
  '/products/azazie-bondi-bermuda-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213112',
  '/products/azazie-bondi-black-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213113',
  '/products/azazie-bondi-blushing-pink-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213115',
  '/products/azazie-bondi-bridesmaid-dress',
  '/products/azazie-bondi-burgundy-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213116',
  '/products/azazie-bondi-champagne-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213123',
  '/products/azazie-bondi-dark-green-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213125',
  '/products/azazie-bondi-dusty-blue-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213129?is_plus_size=1',
  '/products/azazie-bondi-dusty-rose-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213131',
  '/products/azazie-bondi-dusty-sage-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213132',
  '/products/azazie-bondi-eucalyptus-a-line-ruffled-chiffon-floor-length-bridesmaid-dress',
  '/products/azazie-bondi-eucalyptus-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213133',
  '/products/azazie-bondi-lilac-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213144',
  '/products/azazie-bondi-matcha-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/219975',
  '/products/azazie-bondi-mist-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213147',
  '/products/azazie-bondi-paprika-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213152',
  '/products/azazie-bondi-sky-blue-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213169',
  '/products/azazie-bondi-steel-blue-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213171',
  '/products/azazie-bondi-terracotta-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213177',
  '/products/azazie-bondi-twilight-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213178',
  '/products/azazie-bondi-wisteria-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/212668',
  '/products/azazie-bonnie-coral-a-line-keyhole-ruched-chiffon-floor-length-bridesmaid-dress/158071',
  '/products/azazie-bonnie-dusty-sage-a-line-keyhole-ruched-chiffon-floor-length-bridesmaid-dress/158075',
  '/products/azazie-botanica-diamond-white-champagne-a-line-lace-tulle-chapel-train-wedding-dress/223320',
  '/products/azazie-brandie-dark-navy-a-line-pleated-stretch-chiffon-floor-length-bridesmaid-dress/197770',
  // '/products/azazie-bridal-party-swatches',
  '/products/azazie-brielle-dusty-blue-a-line-cowl-spaghetti-straps-stretch-satin-floor-length-bridesmaid-dress/232605',
  '/products/azazie-brooke-champagne-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/127966',
  '/products/azazie-brooke-eucalyptus-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/217566',
  '/products/azazie-brooke-mist-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/127990',
  '/products/azazie-brooke-sky-blue-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/127988',
  '/products/azazie-brookelle-black-sheath-sweetheart-corset-stretch-satin-floor-length-bridesmaid-dress/206300',
  '/products/azazie-brynlee-diamond-white-champagne-a-line-lace-tulle-sweep-train-wedding-dress/221841',
  '/products/azazie-calanthe-dark-navy-a-line-scoop-chiffon-floor-length-mother-of-the-bride-dress/197552',
  '/products/azazie-calanthe-dark-navy-a-line-scoop-chiffon-floor-length-mother-of-the-bride-dress/197552?is_plus_size=1',
  '/products/azazie-calanthe-taupe-a-line-scoop-chiffon-floor-length-mother-of-the-bride-dress/197549',
  '/products/azazie-calanthe-taupe-a-line-scoop-chiffon-floor-length-mother-of-the-bride-dress/197549?is_plus_size=1',
  '/products/azazie-calliana-diamond-white-a-line-v-neck-mikado-chapel-train-wedding-dress/200515',
  '/products/azazie-camlynn-diamond-white-champagne-mermaid-v-neck-sequins-tulle-cathedral-train-wedding-dress/223316',
  '/products/azazie-cammina-diamond-white-a-line-sequins-tulle-chapel-train-wedding-dress/208995',
  '/products/azazie-carmella-diamond-white-a-line-sequins-chiffon-chapel-train-wedding-dress/225145',
  '/products/azazie-carmen-dusk-sheath-lace-floor-length-mother-of-the-bride-dress/228851',
  '/products/azazie-carmena-taupe-a-line-sequins-chiffon-floor-length-mother-of-the-bride-dress/204755',
  '/products/azazie-carson-dark-navy-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/107112',
  '/products/azazie-caymus-diamond-white-a-line-scoop-pleated-crepe-back-satin-chapel-train-wedding-dress/208998',
  '/products/azazie-cecily-desert-rose-sheath-stretch-crepe-knee-length-mother-of-the-bride-dress/201058',
  '/products/azazie-celie-diamond-white-mermaid-v-neck-crepe-back-satin-cathedral-train-wedding-dress/204438',
  '/products/azazie-ceres-dusty-rose-ball-gown-lace-tulle-asymmetrical-flower-girl-dress/232178',
  '/products/azazie-ceres-ivory-ball-gown-lace-tulle-asymmetrical-flower-girl-dress/232179',
  '/products/azazie-chanel-amethyst-a-line-pleated-chiffon-floor-length-bridesmaid-dress/200336',
  '/products/azazie-chanel-black-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190719',
  '/products/azazie-chanel-bridesmaid-dress',
  '/products/azazie-chanel-burgundy-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190722',
  '/products/azazie-chanel-dark-navy-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190732',
  '/products/azazie-chanel-dusty-blue-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190735',
  '/products/azazie-chanel-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190738',
  '/products/azazie-chanel-eucalyptus-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190739',
  '/products/azazie-chanel-matcha-a-line-pleated-chiffon-floor-length-bridesmaid-dress/219927',
  '/products/azazie-chanel-mist-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190754',
  '/products/azazie-charissa-burgundy-sheath-corset-pleated-mesh-floor-length-bridesmaid-dress/218783',
  '/products/azazie-charissa-dusty-sage-sheath-corset-pleated-mesh-floor-length-bridesmaid-dress/218797',
  '/products/azazie-charissa-eucalyptus-sheath-corset-pleated-mesh-floor-length-bridesmaid-dress/218867',
  '/products/azazie-charlize-black-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184264',
  '/products/azazie-charlize-bridesmaid-dress',
  '/products/azazie-charlize-burgundy-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184292',
  '/products/azazie-charlize-champagne-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184304',
  '/products/azazie-charlize-dusty-sage-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184260',
  '/products/azazie-charlize-eucalyptus-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/217553',
  '/products/azazie-charlize-eucalyptus-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/217553',
  '/products/azazie-charlize-wisteria-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184281',
  '/products/azazie-cheri-diamond-white-mermaid-sweetheart-sequins-crepe-back-satin-chapel-train-wedding-dress/204441',
  '/products/azazie-cierra-pine-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/216347',
  '/products/azazie-cindy-diamond-white-champagne-a-line-illusion-off-the-shouler-lace-tulle-chapel-train-wedding-dress/122858',
  '/products/azazie-cindy-diamond-white-champagne-a-line-illusion-off-the-shouler-lace-tulle-chapel-train-wedding-dress/122858?is_plus_size=1',
  '/products/azazie-clarice-amethyst-a-line-halter-chiffon-floor-length-bridesmaid-dress/200312',
  '/products/azazie-clarice-black-a-line-halter-chiffon-floor-length-bridesmaid-dress/191357',
  '/products/azazie-clarice-blushing-pink-a-line-halter-chiffon-floor-length-bridesmaid-dress/191359',
  '/products/azazie-clarice-bridesmaid-dress',
  '/products/azazie-clarice-champagne-a-line-halter-chiffon-floor-length-bridesmaid-dress/191366',
  '/products/azazie-clarice-dark-navy-a-line-halter-chiffon-floor-length-bridesmaid-dress/191370',
  '/products/azazie-clarice-dusty-blue-a-line-halter-chiffon-floor-length-bridesmaid-dress/191373',
  '/products/azazie-clarice-dusty-rose-a-line-halter-chiffon-floor-length-bridesmaid-dress/191375',
  '/products/azazie-clarice-dusty-sage-a-line-halter-chiffon-floor-length-bridesmaid-dress/191376',
  '/products/azazie-clarice-eucalyptus-a-line-halter-chiffon-floor-length-bridesmaid-dress/191377',
  '/products/azazie-clarice-lilac-a-line-halter-chiffon-floor-length-bridesmaid-dress/191388',
  '/products/azazie-clarice-matcha-a-line-halter-chiffon-floor-length-bridesmaid-dress/222536',
  '/products/azazie-clarice-pine-a-line-halter-chiffon-floor-length-bridesmaid-dress/191404',
  '/products/azazie-clarice-sky-blue-a-line-halter-chiffon-floor-length-bridesmaid-dress/191414',
  '/products/azazie-clementina-diamond-white-nude-a-line-v-neck-sequins-stretch-crepe-chapel-train-wedding-dress/206926',
  '/products/azazie-cleobella-black-a-line-sweetheart-lace-chiffon-floor-length-bridesmaid-dress/191900',
  '/products/azazie-cleobella-bridesmaid-dress',
  '/products/azazie-cleobella-champagne-a-line-sweetheart-lace-chiffon-floor-length-bridesmaid-dress/191904',
  '/products/azazie-cleobella-dusty-blue-a-line-sweetheart-lace-chiffon-floor-length-bridesmaid-dress/191911',
  '/products/azazie-cleobella-dusty-sage-a-line-sweetheart-lace-chiffon-floor-length-bridesmaid-dress/191914',
  '/products/azazie-cleopatra-diamond-white-mermaid-scoop-sequins-crepe-back-satin-cathedral-train-wedding-dress/202927',
  '/products/azazie-cora-bridesmaid-dress',
  '/products/azazie-cora-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/118444',
  '/products/azazie-cornelia-taupe-sheath-square-neckline-sequins-chiffon-floor-length-mother-of-the-bride-dress/204750',
  '/products/azazie-cressida-diamond-white-champagne-ball-gown-lace-tulle-chapel-train-wedding-dress/231352',
  '/products/azazie-daenerys-dusty-blue-a-line-cowl-chiffon-floor-length-bridesmaid-dress/115080',
  '/products/azazie-daenerys-sky-blue-a-line-cowl-chiffon-floor-length-bridesmaid-dress/115116',
  '/products/azazie-daira-diamond-white-mermaid-scoop-pleated-crepe-back-satin-chapel-train-wedding-dress/188326',
  '/products/azazie-dalilah-black-a-line-v-neck-pleated-stretch-satin-floor-length-bridesmaid-dress/205911',
  '/products/azazie-dallas-black-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/172401',
  '/products/azazie-dallas-blushing-pink-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/172386',
  '/products/azazie-dallas-champagne-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/172389',
  '/products/azazie-davis-black-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/109260',
  '/products/azazie-davis-bridesmaid-dress',
  '/products/azazie-davis-champagne-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/109267',
  '/products/azazie-davis-dusty-blue-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/109258',
  '/products/azazie-davis-dusty-rose-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/109276',
  '/products/azazie-davis-dusty-sage-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/109277',
  '/products/azazie-davis-eucalyptus-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/188425',
  '/products/azazie-davis-matcha-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/222508',
  '/products/azazie-deandra-bridesmaid-dress',
  '/products/azazie-deandra-champagne-mermaid-pleated-mesh-floor-length-bridesmaid-dress/190927',
  '/products/azazie-deandra-dusty-sage-mermaid-pleated-mesh-floor-length-bridesmaid-dress/190936',
  '/products/azazie-deandra-eucalyptus-mermaid-pleated-mesh-floor-length-bridesmaid-dress/217579',
  '/products/azazie-delaina-diamond-white-champagne-a-line-v-neck-sequins-tulle-cathedral-train-wedding-dress/192554',
  '/products/azazie-delfina-diamond-white-a-line-v-neck-pleated-chiffon-knee-length-wedding-dress/211298',
  '/products/azazie-denice-black-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209888',
  '/products/azazie-denice-blushing-pink-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209890',
  '/products/azazie-denice-cabernet-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209893',
  '/products/azazie-denice-dusty-sage-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209906',
  '/products/azazie-denice-lilac-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209917',
  '/products/azazie-denice-sky-blue-sheath-pleated-chiffon-floor-length-bridesmaid-dress/209936',
  '/products/azazie-denise-diamond-white-champagne-mermaid-sequins-tulle-chapel-train-wedding-dress/211458',
  '/products/azazie-devi-diamond-white-champagne-a-line-v-neck-lace-tulle-chapel-train-wedding-dress/165860',
  '/products/azazie-devonna-diamond-white-champagne-sheath-v-neck-sequins-lace-floor-length-wedding-dress/194987',
  '/products/azazie-digital-gift-card',
  '/products/azazie-digital-gift-card/206953',
  '/products/azazie-dion-black-sheath-scoop-chiffon-floor-length-mother-of-the-bride-dress/113762',
  '/products/azazie-dion-twilight-sheath-scoop-chiffon-floor-length-mother-of-the-bride-dress/149908',
  '/products/azazie-dori-diamond-white-champagne-a-line-lace-tulle-cathedral-train-wedding-dress/227992',
  '/products/azazie-dunja-champagne-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/124611',
  '/products/azazie-dunja-champagne-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/124611?is_plus_size=1',
  '/products/azazie-dysis-diamond-white-champagne-a-line-halter-sequins-tulle-chapel-train-wedding-dress/199498',
  '/products/azazie-ebony-diamond-white-a-line-sequins-crepe-back-satin-chapel-train-wedding-dress/155376',
  '/products/azazie-edelin-dark-navy-a-line-sweetheart-neckline-pleated-mesh-floor-length-mother-of-the-bride-dress/109964',
  '/products/azazie-edelin-dusty-blue-a-line-sweetheart-neckline-pleated-mesh-floor-length-mother-of-the-bride-dress/109967',
  '/products/azazie-elana-dusty-blue-sheath-side-slit-stretch-satin-floor-length-bridesmaid-dress/205379',
  '/products/azazie-ellison-diamond-white-ball-gown-lace-tulle-ankle-length-flower-girl-dress/106207',
  '/products/azazie-elly-black-a-line-lace-v-neck-chiffon-floor-length-bridesmaid-dress/203707',
  '/products/azazie-elly-dusty-sage-a-line-lace-v-neck-chiffon-floor-length-bridesmaid-dress/203722',
  '/products/azazie-elvira-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/202308',
  '/products/azazie-emerald-bridesmaid-dress',
  '/products/azazie-emerald-lilac-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/191001',
  '/products/azazie-emerald-wisteria-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/191041',
  '/products/azazie-endora-blushing-pink-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146253',
  '/products/azazie-endora-cabernet-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146247',
  '/products/azazie-endora-champagne-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146251',
  '/products/azazie-endora-dark-navy-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146258',
  '/products/azazie-endora-dusk-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146260',
  '/products/azazie-endora-dusty-sage-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146261',
  '/products/azazie-endora-mother-of-the-bride-dress',
  '/products/azazie-endora-stormy-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146300',
  '/products/azazie-endora-taupe-a-line-scoop-lace-chiffon-asymmetrical-mother-of-the-bride-dress/146303',
  '/products/azazie-eren-agave-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/198905',
  '/products/azazie-eren-black-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/206190',
  '/products/azazie-eren-bronzer-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/200133',
  '/products/azazie-eren-cedar-rose-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/206189',
  '/products/azazie-eren-dusty-blue-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/198900',
  '/products/azazie-eren-eucalyptus-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/206192',
  '/products/azazie-eren-matcha-mermaid-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/221139',
  '/products/azazie-essy-diamond-white-a-line-v-neck-sequins-tulle-cathedral-train-wedding-dress/192598',
  '/products/azazie-estelle-diamond-white-a-line-pleated-chiffon-chapel-train-wedding-dress/209001',
  '/products/azazie-estephanie-diamond-white-mermaid-sequins-stretch-crepe-cathedral-train-wedding-dress/226877',
  '/products/azazie-estephanie-diamond-white-nude-mermaid-sequins-stretch-crepe-cathedral-train-wedding-dress/227962',
  '/products/azazie-evalleen-bridesmaid-dress',
  '/products/azazie-evalleen-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/147272',
  '/products/azazie-everest-pine-a-line-pleated-chiffon-floor-length-bridesmaid-dress/189360',
  '/products/azazie-evergarden-diamond-white-champagne-a-line-sequins-tulle-cathedral-train-wedding-dress/211032',
  '/products/azazie-fahren-diamond-white-mermaid-cowl-neckline-lace-stretch-satin-chapel-train-wedding-dress/194272',
  '/products/azazie-farren-blushing-pink-a-line-convertible-chiffon-floor-length-bridesmaid-dress/118859',
  '/products/azazie-farren-eucalyptus-a-line-convertible-chiffon-floor-length-bridesmaid-dress/190352',
  '/products/azazie-fatemah-dark-navy-mermaid-scoop-lace-lace-floor-length-mother-of-the-bride-dress/222377',
  '/products/azazie-fawn-diamond-white-a-line-sweetheart-sequins-chiffon-sweep-train-wedding-dress/190553',
  '/products/azazie-fifi-dusty-blue-a-line-convertible-chiffon-floor-length-bridesmaid-dress/174220?is_plus_size=1',
  '/products/azazie-florentina-diamond-white-nude-a-line-sweetheart-sequins-tulle-chapel-train-wedding-dress/206919',
  '/products/azazie-flori-sky-blue-sheath-square-neckline-chiffon-floor-length-bridesmaid-dress/222077',
  '/products/azazie-florian-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/203002',
  '/products/azazie-florine-diamond-white-v-neck-lace-lace-chiffon-wedding-dress-jumpsuit/115915',
  '/products/azazie-flower-wisteria-a-line-pleated-chiffon-floor-length-junior-bridesmaid-dress/140612',
  '/products/azazie-flynn-dusty-rose-a-line-boatneck-lace-tulle-tea-length-mother-of-the-bride-dress/116279',
  '/products/azazie-galilea-dark-navy-mermaid-v-neck-metallic-mesh-floor-length-mother-of-the-bride-dress/232694',
  '/products/azazie-galilea-rose-gold-mermaid-v-neck-metallic-mesh-floor-length-mother-of-the-bride-dress/232696',
  '/products/azazie-gemma-diamond-white-champagne-mermaid-sweetheart-sequins-lace-chapel-train-wedding-dress/223323',
  '/products/azazie-georgette-lavender-a-line-lace-tulle-floor-length-junior-bridesmaid-dress/176209',
  '/products/azazie-gertrude-burgundy-a-line-lace-chiffon-sweep-train-bridesmaid-dress/121029',
  '/products/azazie-gina-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/222484',
  '/products/azazie-ginger-dusty-sage-a-line-halter-pleated-chiffon-floor-length-bridesmaid-dress/150965',
  '/products/azazie-goddess-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/225223',
  '/products/azazie-gracen-diamond-white-nude-mermaid-v-neck-lace-tulle-chapel-train-wedding-dress/163433',
  '/products/azazie-guinevere-diamond-white-mermaid-sequins-stretch-crepe-chapel-train-wedding-dress/226878',
  '/products/azazie-harper-blushing-pink-a-line-pleated-chiffon-floor-length-bridesmaid-dress/134000',
  '/products/azazie-harper-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/133955',
  '/products/azazie-harper-pine-a-line-pleated-chiffon-floor-length-bridesmaid-dress/134023',
  '/products/azazie-hayek-blushing-pink-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/149228',
  '/products/azazie-hayek-blushing-pink-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/149228?is_plus_size=1',
  '/products/azazie-hayes-diamond-white-champagne-mermaid-v-neck-lace-chapel-train-wedding-dress/200562',
  '/products/azazie-hera-dark-navy-a-line-lace-capelet-chiffon-floor-length-mother-of-the-bride-dress/232624',
  '/products/azazie-hera-dusty-rose-a-line-lace-capelet-chiffon-floor-length-mother-of-the-bride-dress/232628',
  '/products/azazie-ida-pine-pleated-stretch-chiffon-bridesmaid-dress-jumpsuit-with-pockets/203635',
  '/products/azazie-iden-diamond-white-mermaid-v-neck-stretch-crepe-sweep-train-wedding-dress/211305',
  '/products/azazie-idony-diamond-white-nude-a-line-v-neck-sequins-sequins-court-train-wedding-dress/220426',
  '/products/azazie-iman-eucalyptus-a-line-a-line-ruched-chiffon-floor-length-bridesmaid-dress/190374',
  '/products/azazie-indie-diamond-white-sheath-v-neck-tulle-chapel-train-wedding-dress/192267',
  '/products/azazie-iris-diamond-white-ball-gown-sequins-tulle-chapel-train-wedding-dress/221811',
  '/products/azazie-isa-eucalyptus-a-line-v-neck-pleated-chiffon-floor-length-mother-of-the-bride-dress/222288',
  '/products/azazie-isabella-diamond-white-mermaid-pleated-crepe-back-satin-chapel-train-wedding-dress/227949',
  '/products/azazie-janine-eucalyptus-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/188381',
  '/products/azazie-jesaphine-black-sheath-ruched-mesh-floor-length-bridesmaid-dress/232742',
  '/products/azazie-jesaphine-dark-navy-sheath-ruched-mesh-floor-length-bridesmaid-dress/232747',
  '/products/azazie-jesaphine-dusty-sage-sheath-ruched-mesh-floor-length-bridesmaid-dress/232750',
  '/products/azazie-joan-champagne-sheath-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/107298',
  '/products/azazie-joie-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/163583',
  '/products/azazie-jovana-diamond-white-a-line-scoop-tulle-chapel-train-wedding-dress/218418',
  '/products/azazie-kaitlynn-dusty-blue-empire-v-neck-ruched-chiffon-floor-length-bridesmaid-dress/158387',
  '/products/azazie-kaitlynn-mist-empire-v-neck-ruched-chiffon-floor-length-bridesmaid-dress/158402',
  '/products/azazie-kalea-bridesmaid-dress',
  '/products/azazie-kaleigh-black-a-line-pleated-chiffon-floor-length-bridesmaid-dress/158313',
  '/products/azazie-kaleigh-rose-petal-a-line-pleated-chiffon-floor-length-bridesmaid-dress/158345',
  '/products/azazie-kaleigh-sky-blue-a-line-pleated-chiffon-floor-length-bridesmaid-dress/158327',
  '/products/azazie-kara-modest-bridesmaid-dresses',
  '/products/azazie-katiya-diamond-white-sheath-cowl-neckline-pleated-stretch-satin-knee-length-wedding-dress/211304',
  '/products/azazie-kaylee-dusty-sage-a-line-chiffon-floor-length-junior-bridesmaid-dress-with-belt/193791',
  '/products/azazie-kenzi-dusty-blue-pleated-chiffon-bridesmaid-dress-jumpsuit/185070',
  '/products/azazie-keyla-eucalyptus-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/192110',
  '/products/azazie-khloe-diamond-white-sheath-sweetheart-neckline-stretch-crepe-floor-length-wedding-dress/214048',
  '/products/azazie-kimber-agave-a-line-flounce-sleeve-chiffon-floor-length-bridesmaid-dress/196553',
  '/products/azazie-kimber-agave-a-line-flounce-sleeve-chiffon-floor-length-bridesmaid-dress/196553?is_plus_size=1',
  '/products/azazie-kimber-bridesmaid-dress',
  '/products/azazie-kimber-dusty-sage-a-line-flounce-sleeve-chiffon-floor-length-bridesmaid-dress/196555',
  '/products/azazie-kimmarie-diamond-white-sand-a-line-v-neck-sequins-chiffon-chapel-train-wedding-dress/223497',
  '/products/azazie-kingsley-dusty-blue-a-line-lace-chiffon-floor-length-bridesmaid-dress/189540',
  '/products/azazie-klaus-taupe-a-line-scoop-sequins-chiffon-knee-length-mother-of-the-bride-dress/199914',
  '/products/azazie-knox-blushing-pink-a-line-v-neck-chiffon-asymmetrical-mother-of-the-bride-dress/191811',
  '/products/azazie-kora-eucalyptus-a-line-convertible-chiffon-floor-length-bridesmaid-dress/197955',
  '/products/azazie-kora-matcha-a-line-convertible-chiffon-floor-length-bridesmaid-dress/219747',
  '/products/azazie-kora-paprika-a-line-convertible-chiffon-floor-length-bridesmaid-dress/167985',
  '/products/azazie-lanei-diamond-white-a-line-v-neck-lace-floor-length-wedding-dress/211300',
  '/products/azazie-lani-eucalyptus-a-line-flounce-sleeve-stretch-satin-floor-length-bridesmaid-dress/206264',
  '/products/azazie-larissa-diamond-white-mermaid-v-neck-stretch-satin-chapel-train-wedding-dress/202925',
  '/products/azazie-laurie-champagne-mermaid-scoop-sequins-tulle-floor-length-mother-of-the-bride-dress/109730',
  '/products/azazie-laurie-dark-navy-mermaid-scoop-sequins-tulle-floor-length-mother-of-the-bride-dress/109734',
  '/products/azazie-laurie-taupe-mermaid-scoop-sequins-tulle-floor-length-mother-of-the-bride-dress/109763',
  '/products/azazie-laylah-diamond-white-mermaid-sweetheart-neckline-chiffon-chapel-train-wedding-dress/214045',
  '/products/azazie-leandra-dark-green-mermaid-v-neck-pleated-mesh-floor-length-bridesmaid-dress/197747',
  '/products/azazie-leila-diamond-white-nude-a-line-v-neck-sequins-tulle-cathedral-train-wedding-dress/223503',
  '/products/azazie-lennon-dusty-blue-a-line-lace-chiffon-floor-length-bridesmaid-dress/111881',
  '/products/azazie-leo-black-mermaid-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/225518',
  '/products/azazie-leo-dusty-blue-mermaid-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/225533',
  '/products/azazie-leo-dusty-sage-mermaid-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/225536',
  '/products/azazie-leonia-black-a-line-long-sleeve-chiffon-floor-length-bridesmaid-dress/216595',
  '/products/azazie-leonia-dusty-blue-a-line-long-sleeve-chiffon-floor-length-bridesmaid-dress/216609',
  '/products/azazie-leonia-dusty-sage-a-line-long-sleeve-chiffon-floor-length-bridesmaid-dress/216612',
  '/products/azazie-leonia-eucalyptus-a-line-long-sleeve-chiffon-floor-length-bridesmaid-dress/216613',
  '/products/azazie-leonie-diamond-white-champagne-mermaid-v-neck-sequins-tulle-cathedral-train-wedding-dress/199495',
  '/products/azazie-leonis-black-mermaid-pleated-stretch-satin-floor-length-bridesmaid-dress/228623',
  '/products/azazie-leonis-dusty-blue-mermaid-pleated-stretch-satin-floor-length-bridesmaid-dress/227975',
  '/products/azazie-leonis-eucalyptus-mermaid-pleated-stretch-satin-floor-length-bridesmaid-dress/228631',
  '/products/azazie-liana-diamond-white-champagne-a-line-v-neck-sequins-tulle-tea-length-wedding-dress/190451',
  '/products/azazie-lianna-diamond-white-champagne-mermaid-lace-chapel-train-wedding-dress/116069',
  '/products/azazie-lianne-bridesmaid-dress',
  '/products/azazie-lianne-dusty-blue-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/119911',
  '/products/azazie-lianne-dusty-sage-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/119914',
  '/products/azazie-lianne-eucalyptus-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/188383',
  '/products/azazie-lianne-eucalyptus-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/188383?is_plus_size=1',
  '/products/azazie-libby-dark-navy-a-line-scoop-sequins-chiffon-floor-length-mother-of-the-bride-dress/110723',
  '/products/azazie-libby-steel-grey-a-line-scoop-sequins-chiffon-floor-length-mother-of-the-bride-dress/110764',
  '/products/azazie-lilith-diamond-white-a-line-sweetheart-lace-chiffon-chapel-train-wedding-dress/122332',
  '/products/azazie-linnea-diamond-white-a-line-scoop-chiffon-chapel-train-wedding-dress/171095',
  '/products/azazie-loey-diamond-white-sheath-sweetheart-neckline-stretch-satin-ankle-length-wedding-dress/211302',
  '/products/azazie-loey-wedding-dress',
  '/products/azazie-lolly-diamond-white-a-line-sequins-chiffon-cathedral-train-wedding-dress/183016',
  '/products/azazie-lorenza-diamond-white-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/146545',
  '/products/azazie-loretta-dark-navy-a-line-cowl-cape-metallic-mesh-floor-length-mother-of-the-bride-dress/232401',
  '/products/azazie-luisa-champagne-mermaid-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/179360',
  '/products/azazie-luisa-dark-navy-mermaid-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/179363',
  '/products/azazie-luxia-diamond-white-a-line-sweetheart-neckline-matte-satin-cathedral-train-wedding-dress/188324',
  '/products/azazie-luz-dusty-sage-a-line-lace-chiffon-floor-length-bridesmaid-dress/112447',
  '/products/azazie-maci-black-a-line-v-neck-pleated-stretch-satin-floor-length-bridesmaid-dress/206466',
  '/products/azazie-macy-dusk-a-line-v-neck-sequin-lace-lace-floor-length-mother-of-the-bride-dress/165400',
  '/products/azazie-macy-dusk-a-line-v-neck-sequin-lace-lace-floor-length-mother-of-the-bride-dress/165400?is_plus_size=1',
  '/products/azazie-mai-black-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228223',
  '/products/azazie-mai-blushing-pink-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228225',
  '/products/azazie-mai-champagne-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228232',
  '/products/azazie-mai-dark-navy-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228235',
  '/products/azazie-mai-dusty-blue-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228238',
  '/products/azazie-mai-dusty-rose-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228240',
  '/products/azazie-mai-dusty-sage-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228241',
  '/products/azazie-mai-eucalyptus-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228242',
  '/products/azazie-mai-lilac-sheath-pleated-chiffon-floor-length-bridesmaid-dress/228250',
  '/products/azazie-maia-diamond-white-champagne-a-line-off-the-shoulder-tulle-chapel-train-wedding-dress/227987',
  '/products/azazie-maive-dusty-blue-sheath-pleated-ruffle-chiffon-floor-length-bridesmaid-dress/223999',
  '/products/azazie-maive-eucalyptus-sheath-pleated-ruffle-chiffon-floor-length-bridesmaid-dress/224003',
  '/products/azazie-maive-lilac-sheath-pleated-ruffle-chiffon-floor-length-bridesmaid-dress/224011',
  '/products/azazie-maive-sky-blue-sheath-pleated-ruffle-chiffon-floor-length-bridesmaid-dress/224036',
  '/products/azazie-marchella-juniper-a-line-pleated-stretch-satin-floor-length-bridesmaid-dress/221274',
  '/products/azazie-maren-allure-black-a-line-v-neck-lace-chiffon-floor-length-bridesmaid-dress/171952',
  '/products/azazie-maren-allure-blushing-pink-a-line-v-neck-lace-chiffon-floor-length-bridesmaid-dress/171926',
  '/products/azazie-maren-allure-twilight-a-line-v-neck-lace-chiffon-floor-length-bridesmaid-dress/171990',
  '/products/azazie-marge-cabernet-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201749',
  '/products/azazie-marge-champagne-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201752',
  '/products/azazie-marge-champagne-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201752?is_plus_size=1',
  '/products/azazie-marge-dark-navy-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201756',
  '/products/azazie-marge-dusty-blue-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201760',
  '/products/azazie-marge-dusty-sage-a-line-scoop-lace-chiffon-tea-length-mother-of-the-bride-dress/201763',
  '/products/azazie-mari-diamond-white-mermaid-v-neck-stretch-crepe-sweep-train-wedding-dress/204440',
  '/products/azazie-marianne-black-sheath-v-neck-pleated-chiffon-floor-length-mother-of-the-bride-dress/195371',
  '/products/azazie-marisela-diamond-white-a-line-sequins-crepe-back-satin-chapel-train-wedding-dress/226880',
  '/products/azazie-maritza-dark-green-a-line-pleated-matte-satin-tea-length-mother-of-the-bride-dress/228865',
  '/products/azazie-maritza-dusty-blue-a-line-pleated-matte-satin-tea-length-mother-of-the-bride-dress/228868',
  '/products/azazie-marlin-diamond-white-mermaid-off-the-shoulder-satin-cathedral-train-wedding-dress/167429',
  '/products/azazie-maron-dusty-blue-a-line-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/196602',
  '/products/azazie-maron-matcha-a-line-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/221055',
  '/products/azazie-mary-dark-navy-a-line-side-slit-chiffon-floor-length-mother-of-the-bride-dress/230256',
  '/products/azazie-mary-dark-navy-a-line-side-slit-chiffon-floor-length-mother-of-the-bride-dress/230256?is_plus_size=1',
  '/products/azazie-mary-dusty-blue-a-line-side-slit-chiffon-floor-length-mother-of-the-bride-dress/230259',
  '/products/azazie-marybell-ivory-a-line-bow-tulle-ankle-length-flower-girl-dress/206119',
  '/products/azazie-marybell-white-a-line-bow-tulle-ankle-length-flower-girl-dress/206120',
  '/products/azazie-marzia-black-sheath-cowl-pleated-stretch-satin-floor-length-bridesmaid-dress/206285',
  '/products/azazie-maura-dusk-sequins-lace-chiffon-mother-of-the-bride-dress-jumpsuit-pantsuit/108250',
  '/products/azazie-maura-dusk-sequins-lace-chiffon-mother-of-the-bride-dress-jumpsuit-pantsuit/108250?is_plus_size=1',
  '/products/azazie-maura-dusty-rose-sequins-lace-chiffon-mother-of-the-bride-dress-jumpsuit-pantsuit/108252',
  '/products/azazie-maura-mother-of-the-bride-dress',
  '/products/azazie-mei-english-rose-a-line-v-neck-stretch-satin-floor-length-bridesmaid-dress/198480',
  '/products/azazie-mel-amethyst-sheath-long-sleeve-stretch-satin-floor-length-bridesmaid-dress/229621',
  '/products/azazie-melena-black-champagne-mermaid-lace-tulle-floor-length-mother-of-the-bride-dress/200056',
  '/products/azazie-melrose-diamond-white-champagne-a-line-sweetheart-lace-tulle-chapel-train-wedding-dress/146803',
  '/products/azazie-memphis-diamond-white-nude-mermaid-v-neck-sequins-lace-chapel-train-wedding-dress/197242',
  '/products/azazie-mero-black-sheath-pleated-stretch-satin-floor-length-bridesmaid-dress/227250',
  '/products/azazie-mero-dusty-blue-sheath-pleated-stretch-satin-floor-length-bridesmaid-dress/227246',
  '/products/azazie-mero-eucalyptus-sheath-pleated-stretch-satin-floor-length-bridesmaid-dress/227256',
  '/products/azazie-mero-matcha-sheath-pleated-stretch-satin-floor-length-bridesmaid-dress/227259',
  '/products/azazie-mika-black-sheath-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/206297',
  '/products/azazie-mika-bronzer-sheath-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/204690',
  '/products/azazie-mika-matcha-sheath-one-shoulder-stretch-satin-floor-length-bridesmaid-dress/221076',
  '/products/azazie-mireya-diamond-white-nude-sheath-sequins-tulle-chapel-train-wedding-dress/227969',
  '/products/azazie-mirra-taupe-sheath-scoop-pleated-chiffon-knee-length-mother-of-the-bride-dress/222368',
  '/products/azazie-mistie-diamond-white-mermaid-v-neck-sequins-stretch-crepe-cathedral-train-wedding-dress/194279',
  '/products/azazie-moira-dusty-blue-a-line-scoop-chiffon-floor-length-bridesmaid-dress/119995',
  '/products/azazie-molly-black-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/148537',
  '/products/azazie-montclair-diamond-white-frost-a-line-organza-chapel-train-wedding-dress/204334',
  '/products/azazie-moonlight-diamond-white-mermaid-scoop-pleated-crepe-back-satin-chapel-train-wedding-dress/202921&is_plus_size=1',
  '/products/azazie-moonlight-diamond-white-mermaid-scoop-pleated-crepe-back-satin-chapel-train-wedding-dress/202921',
  '/products/azazie-moonlight-diamond-white-mermaid-scoop-pleated-crepe-back-satin-chapel-train-wedding-dress/202921?is_plus_size=1',
  '/products/azazie-muni-ivory-a-line-bow-tulle-ankle-length-flower-girl-dress/216963',
  '/products/azazie-naeem-agave-a-line-v-neck-ruffle-chiffon-floor-length-bridesmaid-dress/108822',
  '/products/azazie-narine-stormy-a-line-high-neckline-pleated-chiffon-floor-length-mother-of-the-bride-dress/226230',
  '/products/azazie-neve-pine-ball-gown-stretch-satin-floor-length-bridesmaid-dress-with-pockets/228393',
  '/products/azazie-nikita-diamond-white-champagne-a-line-sequins-tulle-chapel-train-wedding-dress/168756',
  '/products/azazie-noella-black-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/223606',
  '/products/azazie-norah-eucalyptus-a-line-v-neck-long-sleeve-chiffon-floor-length-bridesmaid-dress/232706',
  '/products/azazie-norah-eucalyptus-a-line-v-neck-long-sleeve-chiffon-floor-length-bridesmaid-dress/232706?is_plus_size=1',
  '/products/azazie-nylah-diamond-white-nude-a-line-sequins-tulle-chapel-train-wedding-dress/229821',
  '/products/azazie-nyx-diamond-white-champagne-mermaid-v-neck-sequins-stretch-satin-chapel-train-wedding-dress/201676',
  '/products/azazie-oaklee-diamond-white-sheath-one-shoulder-stretch-satin-floor-length-wedding-dress/211296',
  '/products/azazie-ocean-pine-a-line-v-neck-pleated-stretch-satin-floor-length-bridesmaid-dress/205948',
  '/products/azazie-ohara-steel-grey-a-line-v-neck-chiffon-floor-length-mother-of-the-bride-dress/219177',
  '/products/azazie-oksana-black-a-line-v-neck-pleated-chiffon-floor-length-mother-of-the-bride-dress/222399',
  '/products/azazie-oksana-black-a-line-v-neck-pleated-chiffon-floor-length-mother-of-the-bride-dress/222399?is_plus_size=1',
  '/products/azazie-oliniana-stormy-mermaid-lace-mesh-floor-length-mother-of-the-bride-dress/231472',
  '/products/azazie-olivia-dusty-blue-a-line-square-neckline-pleated-chiffon-knee-length-mother-of-the-bride-dress/126738',
  '/products/azazie-olivia-dusty-rose-a-line-square-neckline-pleated-chiffon-knee-length-mother-of-the-bride-dress/126739',
  '/products/azazie-olivia-dusty-sage-a-line-square-neckline-pleated-chiffon-knee-length-mother-of-the-bride-dress/126740',
  '/products/azazie-omari-dusty-sage-a-line-chiffon-floor-length-bridesmaid-dress/225911',
  '/products/azazie-omari-lilac-a-line-chiffon-floor-length-bridesmaid-dress/225920',
  '/products/azazie-omari-matcha-a-line-chiffon-floor-length-bridesmaid-dress/225923',
  '/products/azazie-onyx-diamond-white-mermaid-sequins-crepe-back-satin-chapel-train-wedding-dress/210503',
  '/products/azazie-opal-diamond-white-sheath-square-neckline-stretch-crepe-knee-length-wedding-dress/168657',
  '/products/azazie-palana-dark-navy-a-line-lace-chiffon-asymmetrical-mother-of-the-bride-dress/228824',
  '/products/azazie-palana-dusty-blue-a-line-lace-chiffon-asymmetrical-mother-of-the-bride-dress/228827',
  '/products/azazie-palana-dusty-sage-a-line-lace-chiffon-asymmetrical-mother-of-the-bride-dress/228829',
  '/products/azazie-pamela-dusty-sage-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/160562',
  '/products/azazie-peyton-black-a-line-ruched-chiffon-floor-length-bridesmaid-dress/225811',
  '/products/azazie-peyton-eucalyptus-a-line-ruched-chiffon-floor-length-bridesmaid-dress/225830',
  '/products/azazie-porcelain-black-a-line-off-the-shoulder-lace-floor-length-mother-of-the-bride-dress/151647',
  '/products/azazie-porcelain-champagne-a-line-off-the-shoulder-lace-floor-length-mother-of-the-bride-dress/151646',
  '/products/azazie-rae-terracotta-a-line-bow-mesh-floor-length-bridesmaid-dress/230465',
  '/products/azazie-raven-diamond-white-sand-mermaid-side-slit-tulle-sweep-train-wedding-dress/227588',
  '/products/azazie-rinna-black-a-line-one-shoulder-stretch-crepe-floor-length-bridesmaid-dress/163349',
  '/products/azazie-rinna-blushing-pink-a-line-one-shoulder-stretch-crepe-floor-length-bridesmaid-dress/163350',
  '/products/azazie-rinna-sky-blue-a-line-one-shoulder-stretch-crepe-floor-length-bridesmaid-dress/163365',
  '/products/azazie-romy-cabernet-mermaid-v-neck-sequins-tulle-floor-length-mother-of-the-bride-dress/201096',
  '/products/azazie-rorie-black-sheath-one-shoulder-luxe-knit-floor-length-bridesmaid-dress/222002',
  '/products/azazie-rorie-dusty-blue-sheath-one-shoulder-luxe-knit-floor-length-bridesmaid-dress/222004',
  '/products/azazie-rosalina-diamond-white-champagne-mermaid-v-neck-lace-crepe-back-satin-cathedral-train-wedding-dress/205206',
  '/products/azazie-rosemarie-dark-navy-a-line-lace-floor-length-mother-of-the-bride-dress/201088',
  '/products/azazie-rosina-diamond-white-sheath-pleated-stretch-satin-knee-length-wedding-dress/211295',
  '/products/azazie-rowe-cloudy-blue-ball-gown-off-the-shoulder-tulle-chapel-train-wedding-dress/167747',
  '/products/azazie-roya-eucalyptus-mermaid-v-neck-pleated-mesh-floor-length-mother-of-the-bride-dress/222326',
  '/products/azazie-roza-diamond-white-a-line-stretch-satin-tea-length-flower-girl-dress/149885',
  '/products/azazie-rue-black-a-line-halter-chiffon-floor-length-bridesmaid-dress/109167',
  '/products/azazie-rue-bridesmaid-dress',
  '/products/azazie-rue-dusty-blue-a-line-halter-chiffon-floor-length-bridesmaid-dress/109181',
  '/products/azazie-rue-sky-blue-a-line-halter-chiffon-floor-length-bridesmaid-dress/109220',
  '/products/azazie-rylee-bridesmaid-dress',
  '/products/azazie-rylee-dusty-blue-a-line-pleated-chiffon-floor-length-bridesmaid-dress/109062',
  '/products/azazie-sable-diamond-white-a-line-lace-stretch-satin-chapel-train-wedding-dress/215836',
  '/products/azazie-saffron-diamond-white-champagne-mermaid-sweetheart-sequins-stretch-crepe-chapel-train-wedding-dress/161325',
  '/products/azazie-salina-diamond-white-champagne-mermaid-sweetheart-sequins-tulle-chapel-train-wedding-dress/209408',
  '/products/azazie-sanna-dark-navy-champagne-a-line-scoop-lace-tulle-tea-length-mother-of-the-bride-dress/124590',
  '/products/azazie-sanna-dusty-blue-a-line-scoop-lace-tulle-tea-length-mother-of-the-bride-dress/124592',
  '/products/azazie-sanna-dusty-rose-a-line-scoop-lace-tulle-tea-length-mother-of-the-bride-dress/124594',
  '/products/azazie-saturn-dusty-rose-sheath-v-neck-pleated-chiffon-knee-length-mother-of-the-bride-dress/152445',
  '/products/azazie-scarlette-diamond-white-champagne-a-line-sweetheart-lace-chiffon-mini-wedding-dress/212753',
  '/products/azazie-sedona-lavender-mist-ball-gown-tulle-chapel-train-wedding-dress/149552',
  '/products/azazie-seraphine-vintage-mauve-blushing-pink-a-line-sequins-tulle-chapel-train-wedding-dress/227989',
  '/products/azazie-sharen-diamond-white-nude-mermaid-stretch-crepe-chapel-train-wedding-dress/227986',
  '/products/azazie-sharon-black-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress',
  '/products/azazie-sharon-black-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/118583',
  '/products/azazie-shiv-diamond-white-a-line-beaded-crepe-back-satin-chapel-train-wedding-dress/225134',
  '/products/azazie-shonda-dusty-blue-boatneck-pleated-lace-chiffon-asymmetrical-mother-of-the-bride-dress/152187',
  '/products/azazie-shonda-dusty-sage-boatneck-pleated-lace-chiffon-asymmetrical-mother-of-the-bride-dress/152251',
  '/products/azazie-sian-diamond-white-a-line-side-slit-stretch-satin-sweep-train-wedding-dress/225143',
  '/products/azazie-silvia-blushing-pink-a-line-lace-chiffon-floor-length-mother-of-the-bride-dress/113782',
  '/products/azazie-silvia-dark-navy-a-line-lace-chiffon-floor-length-mother-of-the-bride-dress/113784',
  '/products/azazie-singer-dusty-sage-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/110256',
  '/products/azazie-singer-sky-blue-a-line-v-neck-lace-chiffon-floor-length-mother-of-the-bride-dress/110278',
  '/products/azazie-sirena-diamond-white-champagne-mermaid-sweetheart-sequins-tulle-chapel-train-wedding-dress/223318',
  '/products/azazie-snapdragon-dusty-sage-a-line-v-neck-ruched-chiffon-floor-length-mother-of-the-bride-dress/125759',
  '/products/azazie-snapdragon-taupe-a-line-v-neck-ruched-chiffon-floor-length-mother-of-the-bride-dress/125801',
  '/products/azazie-solaris-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/205207',
  '/products/azazie-sommer-dark-navy-a-line-velvet-floor-length-bridesmaid-dress/226801',
  '/products/azazie-sorella-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/161953',
  '/products/azazie-soren-eucalyptus-a-line-pleated-stretch-satin-floor-length-bridesmaid-dress/205955',
  '/products/azazie-soren-matcha-a-line-pleated-stretch-satin-floor-length-bridesmaid-dress/221163',
  '/products/azazie-starlow-diamond-white-mermaid-cowl-neckline-pleated-stretch-satin-chapel-train-wedding-dress/194276',
  '/products/azazie-stellar-dusk-mermaid-signature-sequin-floor-length-bridesmaid-dress/122447',
  '/products/azazie-stevie-diamond-white-nude-a-line-lace-tulle-chapel-train-wedding-dress/159939',
  // '/products/azazie-stretch-crepe-swatch-booklet',
  '/products/azazie-sue-black-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/112635',
  '/products/azazie-summer-blushing-pink-mermaid-scoop-cowl-chiffon-asymmetrical-bridesmaid-dress/148347',
  '/products/azazie-summer-sky-blue-mermaid-scoop-cowl-chiffon-asymmetrical-bridesmaid-dress/148351',
  '/products/azazie-sunbeam-diamond-white-mermaid-beaded-chiffon-asymmetrical-wedding-dress/215868',
  '/products/azazie-susanne-dusty-blue-sheath-lace-floor-length-mother-of-the-bride-dress/229866',
  '/products/azazie-syenna-dusty-blue-a-line-ruched-chiffon-floor-length-bridesmaid-dress/228572',
  '/products/azazie-syenna-dusty-sage-a-line-ruched-chiffon-floor-length-bridesmaid-dress/228575',
  '/products/azazie-tanicia-dusty-blue-a-line-v-neck-pleated-mesh-floor-length-bridesmaid-dress/150082',
  '/products/azazie-tanicia-dusty-sage-a-line-v-neck-pleated-mesh-floor-length-bridesmaid-dress/150058',
  '/products/azazie-tape-measure',
  '/products/azazie-tatiana-diamond-white-champagne-a-line-v-neck-sequins-tulle-chapel-train-wedding-dress/204459',
  '/products/azazie-tayla-black-sheath-square-neckline-chiffon-floor-length-bridesmaid-dress/203836',
  '/products/azazie-tayla-dusty-blue-sheath-square-neckline-chiffon-floor-length-bridesmaid-dress/203851',
  '/products/azazie-tayla-sky-blue-sheath-square-neckline-chiffon-floor-length-bridesmaid-dress/203888',
  '/products/azazie-tessa-black-sheath-sweetheart-off-the-shouler-mesh-floor-length-bridesmaid-dress/201963',
  '/products/azazie-tessa-dusty-sage-sheath-sweetheart-off-the-shouler-mesh-floor-length-bridesmaid-dress/201977',
  '/products/azazie-tessie-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/222528',
  '/products/azazie-tyra-black-mermaid-halter-lace-lace-sweep-train-mother-of-the-bride-dress/212686',
  '/products/azazie-tyra-dark-navy-mermaid-halter-lace-lace-sweep-train-mother-of-the-bride-dress/113461',
  '/products/azazie-tyra-dusty-rose-mermaid-halter-lace-lace-sweep-train-mother-of-the-bride-dress/113459',
  '/products/azazie-vera-dark-navy-a-line-v-neck-pleated-mesh-tea-length-mother-of-the-bride-dress/223570',
  '/products/azazie-vera-matcha-a-line-v-neck-pleated-mesh-tea-length-mother-of-the-bride-dress/231134',
  '/products/azazie-veradis-diamond-white-a-line-v-neck-lace-chiffon-floor-length-wedding-dress/214047',
  '/products/azazie-verna-maternity-bridesmaid-dress',
  '/products/azazie-vienna-diamond-white-champagne-a-line-off-the-shouler-tulle-tea-length-wedding-dress/215838',
  '/products/azazie-vini-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/219512',
  '/products/azazie-violeta-black-ball-gown-bow-matte-satin-tea-length-flower-girl-dress/217832',
  '/products/azazie-violeta-lilac-ball-gown-bow-matte-satin-tea-length-flower-girl-dress/217862',
  '/products/azazie-violette-diamond-white-sheath-v-neck-chiffon-floor-length-wedding-dress/215864',
  '/products/azazie-vivienne-diamond-white-champagne-a-line-sweetheart-lace-sweep-train-wedding-dress/196180',
  '/products/azazie-wedding-garment-bags',
  '/products/azazie-weisz-champagne-a-line-square-neckline-pleated-chiffon-floor-length-mother-of-the-bride-dress/125672',
  '/products/azazie-weisz-champagne-a-line-square-neckline-pleated-chiffon-floor-length-mother-of-the-bride-dress/125672?is_plus_size=1',
  '/products/azazie-wendie-diamond-white-champagne-a-line-sequins-tulle-cathedral-train-wedding-dress/203003',
  '/products/azazie-willa-diamond-white-mermaid-lace-sweep-train-wedding-dress/225141',
  '/products/azazie-x-kendall-kylie-bermuda-cowl-scoop-chiffon-mermaid-bridesmaid-dress/217232',
  '/products/azazie-x-kendall-kylie-dark-navy-off-shoulder-stretch-satin-and-chiffon-sheath-bridesmaid-dress/215783',
  '/products/azazie-x-kendall-kylie-matcha-corseted-chiffon-column-bridesmaid-dress/219956',
  '/products/azazie-xena-diamond-white-a-line-v-neck-sequins-stretch-crepe-chapel-train-wedding-dress/183251',
  '/products/azazie-yetta-maternity-bridesmaid-dress',
  '/products/azazie-yoki-diamond-white-nude-mermaid-scoop-tulle-chapel-train-wedding-dress/190436',
  '/products/azazie-yunifer-diamond-white-mermaid-v-neck-lace-stretch-crepe-chapel-train-wedding-dress/209000',
  '/products/azazie-zapheira-dusty-blue-a-line-ruched-chiffon-floor-length-bridesmaid-dress/150901',
  '/products/azazie-zeya-black-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197447',
  '/products/azazie-zeya-blushing-pink-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197408',
  '/products/azazie-zeya-bridesmaid-dress',
  '/products/azazie-zeya-cabernet-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197393',
  '/products/azazie-zeya-dusty-blue-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197445',
  '/products/azazie-zeya-dusty-sage-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197440',
  '/products/azazie-zeya-eucalyptus-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/197404',
  '/products/azazie-zeya-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/219939',
  '/products/dear-to-my-heart-light-blue-off-the-shoulder-midi-sod-dress/222841?sourceTag=wedding_guest_dresses',
  '/products/forever-lovable-black-floral-embroidered-maxi-sod-dress/213795?sourceTag=wedding_guest_dresses',
  '/products/gentlemen-collection-matte-satin-skinny-tie',
  '/products/gentlemen-collection-matte-satin-vest',
  '/products/gentlemen-collection-matte-satin-wide-tie',
  '/products/gentlemen-collection-men-matte-satin-pre-tied-bow-tie',
  '/products/love-of-romance-french-blue-tie-straps-ruffled-midi-sod-dress/214472?sourceTag=wedding_guest_dresses',
  '/products/love-of-romance-white-tie-straps-ruffled-midi-sod-dress/214468?sourceTag=wedding_guest_dresses',
  '/products/my-dearest-white-lace-sleeveless-midi-sod-dress/213775?sourceTag=events_dresses',
  '/products/on-the-guest-list-blushing-pink-one-shoulder-maxi-sod-dress/213931?sourceTag=wedding_guest_dresses',
  '/products/one-strap-buckle-block-heel-sandals/226511',
  '/products/pleats-elegant-clutch-bag/215795',
  '/products/sample-mother-of-the-bride?style=azazie-endora-mother-of-the-bride-dress',
  '/products/strap-mid-heel-sandals/224464',
  '/products/upstudio-alesandro-dark-navy-mermaid-ruched-jacquard-floor-length-mother-of-the-bride-dress/227739',
  '/products/upstudio-aniston-dark-navy-a-line-pleated-jacquard-asymmetrical-mother-of-the-bride-dress/226358',
  '/products/upstudio-bisbee-blushing-pink-a-line-pleated-jacquard-midi-length-mother-of-the-bride-dress/226357',
  '/products/upstudio-clifton-dark-navy-mermaid-pleated-lace-floor-length-mother-of-the-bride-dress/226382',
  '/products/upstudio-fremont-champagne-a-line-sequins-ballerina-length-mother-of-the-bride-dress/213400',
  '/products/upstudio-hamden-dark-navy-mermaid-bateau-neckline-metallic-knit-floor-length-mother-of-the-bride-dress/222438',
  '/products/upstudio-harrison-rose-gold-mermaid-off-the-shoulder-jacquard-floor-length-mother-of-the-bride-dress/227737',
  '/products/upstudio-joliet-dusty-rose-mermaid-v-neck-polyester-floor-length-mother-of-the-bride-dress/217714',
  '/products/upstudio-lennox-dark-navy-sheath-jacquard-floor-length-mother-of-the-bride-dress/227734',
  '/products/upstudio-menlo-dark-navy-a-line-sequins-floor-length-mother-of-the-bride-dress/226448',
  '/products/upstudio-payne-dusty-blue-mermaid-off-the-shoulder-jacquard-floor-length-mother-of-the-bride-dress/227738',
  '/products/upstudio-petaluma-burgundy-mermaid-v-neck-sequins-floor-length-mother-of-the-bride-dress/214692',
  '/products/upstudio-petaluma-champagne-mermaid-v-neck-sequins-floor-length-mother-of-the-bride-dress/217502',
  '/products/upstudio-petaluma-dark-green-mermaid-v-neck-sequins-floor-length-mother-of-the-bride-dress/217501',
  '/products/upstudio-petaluma-dark-green-mermaid-v-neck-sequins-sequins-floor-length-mother-of-the-bride-dress/217501',
  '/products/upstudio-petaluma-dusty-rose-mermaid-v-neck-sequins-floor-length-mother-of-the-bride-dress/217503',
  '/products/upstudio-sacramento-champagne-a-line-v-neck-ruched-sequins-floor-length-mother-of-the-bride-dress/215207',
  '/products/upstudio-sitka-dark-navy-mermaid-pleated-jacquard-floor-length-mother-of-the-bride-dress/226359',
  '/products/upstudio-stokton-dusty-blue-a-line-boatneck-lace-floor-length-mother-of-the-bride-dress/226354',
  '/products/upstudio-tuscon-agave-a-line-v-neck-ruched-metallic-mesh-asymmetrical-mother-of-the-bride-dress/221661',
  '/products/upstudio-tuscon-champagne-a-line-v-neck-ruched-metallic-mesh-asymmetrical-mother-of-the-bride-dress/223054',
  '/products/upstudio-tuscon-dark-navy-a-line-v-neck-ruched-metallic-mesh-asymmetrical-mother-of-the-bride-dress/224822',
  '/products/upstudio-tuscon-rose-gold-a-line-v-neck-ruched-metallic-mesh-asymmetrical-mother-of-the-bride-dress/222745',
  '/products/upstudio-vandalia-dusty-rose-a-line-v-neck-shimmer-knit-floor-length-mother-of-the-bride-dress/217715',
  '/products/upstudio-visalia-dusty-blue-a-line-boatneck-lace-midi-length-mother-of-the-bride-dress/226356',
  '/products/upstudio-winslow-agave-a-line-v-neck-pleated-metallic-mesh-ankle-length-mother-of-the-bride-dress/222759',
  '/products/upstudio-winslow-mulberry-a-line-v-neck-pleated-metallic-mesh-ankle-length-mother-of-the-bride-dress/222758',
  '/products/upstudio-yuma-mulberry-a-line-metallic-mesh-floor-length-mother-of-the-bride-dress/221662',
  '/products/valdosta-dark-navy-long-sleeve-midi-sod-dress/228009',
  '/products/azazie-alia-dusty-sage-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190808',
  '/products/azazie-avelina-dusty-sage-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/145950',
  '/products/azazie-becca-eucalyptus-sheath-v-neck-chiffon-floor-length-bridesmaid-dress/206699',
  '/products/azazie-bondi-dusty-blue-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213129',
  '/products/azazie-bondi-sunset-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/213174',
  '/products/azazie-bonnie-dusty-sage-a-line-keyhole-ruched-chiffon-floor-length-bridesmaid-dress/158075',
  '/products/azazie-brooke-dusty-sage-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/127983',
  '/products/azazie-chanel-champagne-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190728',
  '/products/azazie-chanel-eucalyptus-a-line-pleated-chiffon-floor-length-bridesmaid-dress/190739',
  '/products/azazie-charlize-burgundy-a-line-one-shoulder-mesh-floor-length-bridesmaid-dress/184292',
  '/products/azazie-clarice-dusty-sage-a-line-halter-chiffon-floor-length-bridesmaid-dress/191376',
  '/products/azazie-dallas-champagne-a-line-one-shoulder-chiffon-floor-length-bridesmaid-dress/172389',
  '/products/azazie-davis-eucalyptus-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/188425',
  '/products/azazie-deandra-dark-green-mermaid-pleated-mesh-floor-length-bridesmaid-dress/190930',
  '/products/azazie-deandra-dusty-sage-mermaid-pleated-mesh-floor-length-bridesmaid-dress/190936',
  '/products/azazie-dominic-pine-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/202145',
  '/products/azazie-elly-burgundy-a-line-lace-v-neck-chiffon-floor-length-bridesmaid-dress/203709',
  '/products/azazie-emerald-blushing-pink-a-line-ruffled-chiffon-floor-length-bridesmaid-dress/190973',
  '/products/azazie-farren-black-a-line-convertible-chiffon-floor-length-bridesmaid-dress/118868',
  '/products/azazie-ginger-eucalyptus-a-line-halter-pleated-chiffon-floor-length-bridesmaid-dress/188439',
  '/products/azazie-harper-pine-a-line-pleated-chiffon-floor-length-bridesmaid-dress/134023',
  '/products/azazie-janine-terracotta-a-line-v-neck-chiffon-floor-length-bridesmaid-dress/119512',
  '/products/azazie-kaleigh-lilac-a-line-pleated-chiffon-floor-length-bridesmaid-dress/158303',
  '/products/azazie-keyla-cabernet-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/135588',
  '/products/azazie-kimber-agave-a-line-flounce-sleeve-chiffon-floor-length-bridesmaid-dress/196553',
  '/products/azazie-kora-lilac-a-line-convertible-chiffon-floor-length-bridesmaid-dress/167939',
  '/products/azazie-kori-eucalyptus-a-line-pleated-chiffon-floor-length-bridesmaid-dress/188431',
  '/products/azazie-leandra-dark-green-mermaid-v-neck-pleated-mesh-floor-length-bridesmaid-dress/197747',
  '/products/azazie-lecia-eucalyptus-empire-off-the-shoulerpleated-chiffon-floor-length-bridesmaid-dress/190390',
  '/products/azazie-lennon-dusty-blue-a-line-lace-chiffon-floor-length-bridesmaid-dress/111881',
  '/products/azazie-leo-blushing-pink-mermaid-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/225520',
  '/products/azazie-lianne-eucalyptus-a-line-off-the-shoulder-chiffon-floor-length-bridesmaid-dress/188383',
  '/products/azazie-luz-desert-rose-a-line-lace-chiffon-floor-length-bridesmaid-dress/112429',
  '/products/azazie-maive-black-sheath-pleated-ruffle-chiffon-floor-length-bridesmaid-dress/223984',
  '/products/azazie-maree-dusk-a-line-lace-chiffon-floor-length-bridesmaid-dress/227937',
  '/products/azazie-mea-dark-green-a-line-lace-chiffon-floor-length-bridesmaid-dress/204703',
  '/products/azazie-memphis-diamond-white-nude-mermaid-v-neck-sequins-lace-chapel-train-wedding-dress/197242',
  '/products/azazie-naeem-agave-a-line-v-neck-ruffle-chiffon-floor-length-bridesmaid-dress/108822',
  '/products/azazie-norah-agave-a-line-v-neck-long-sleeve-chiffon-floor-length-bridesmaid-dress/232789',
  '/products/azazie-rue-sky-blue-a-line-halter-chiffon-floor-length-bridesmaid-dress/109220',
  '/products/azazie-rylee-burgundy-a-line-pleated-chiffon-floor-length-bridesmaid-dress/109050',
  '/products/azazie-temeka-dusty-sage-a-line-ruched-chiffon-floor-length-bridesmaid-dress/147163',
  '/products/azazie-tessie-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/222528',
  '/products/azazie-zeya-matcha-a-line-v-neck-pleated-chiffon-floor-length-bridesmaid-dress/219939',
  '/products/magical-romance-dark-emerald-satin-maxi-sod-dress/213947',
  '/products/sample-brides?style=azazie-florentina-wedding-dress',
  '/products/sample-bridesmaids',
  '/products/sample-bridesmaids?style=azazie-alia',
  '/products/sample-bridesmaids?style=azazie-ashana',
  '/products/sample-bridesmaids?style=azazie-avelina',
  '/products/sample-bridesmaids?style=azazie-becca',
  '/products/sample-bridesmaids?style=azazie-bondi',
  '/products/sample-bridesmaids?style=azazie-bonnie',
  '/products/sample-bridesmaids?style=azazie-chanel',
  '/products/sample-bridesmaids?style=azazie-charlize',
  '/products/sample-bridesmaids?style=azazie-clarice',
  '/products/sample-bridesmaids?style=azazie-cleobella',
  '/products/sample-bridesmaids?style=azazie-dakota',
  '/products/sample-bridesmaids?style=azazie-dallas',
  '/products/sample-bridesmaids?style=azazie-davis',
  '/products/sample-bridesmaids?style=azazie-deandra',
  '/products/sample-bridesmaids?style=azazie-denice',
  '/products/sample-bridesmaids?style=azazie-elly',
  '/products/sample-bridesmaids?style=azazie-emerald',
  '/products/sample-bridesmaids?style=azazie-eren-stretch-satin-dress',
  '/products/sample-bridesmaids?style=azazie-farren',
  '/products/sample-bridesmaids?style=azazie-kaitlynn',
  '/products/sample-bridesmaids?style=azazie-kaleigh',
  '/products/sample-bridesmaids?style=azazie-kimber',
  '/products/sample-bridesmaids?style=azazie-kora',
  '/products/sample-bridesmaids?style=azazie-leo',
  '/products/sample-bridesmaids?style=azazie-lianne',
  '/products/sample-bridesmaids?style=azazie-mai',
  '/products/sample-bridesmaids?style=azazie-maive',
  '/products/sample-bridesmaids?style=azazie-maren-allure',
  '/products/sample-bridesmaids?style=azazie-mero',
  '/products/sample-bridesmaids?style=azazie-naeem',
  '/products/sample-bridesmaids?style=azazie-omari',
  '/products/sample-bridesmaids?style=azazie-peyton',
  '/products/sample-bridesmaids?style=azazie-rue',
  '/products/sample-bridesmaids?style=azazie-rylee',
  '/products/sample-bridesmaids?style=azazie-soren-stretch-satin-dress',
  '/products/sample-bridesmaids?style=azazie-sue',
  '/products/sample-bridesmaids?style=azazie-tayla',
  '/products/sample-bridesmaids?style=azazie-zeya'
]

// 正则匹配 '/all/bridesmaid-dresses*、/all/mother-of-the-bride-dresse*、/all/wedding-dresse*、 /all/atelier*
const RegExpPages = [/\/all\/bridesmaid-dresses*/, /\/all\/mother-of-the-bride-dresse*/, /\/all\/wedding-dresse*/, /\/all\/atelier*/]
// const RegExpPages = [/\/all\/*/]
module.exports = {
  redisAllPages: [...RegExpPages, ...redisPages, ...redisListSod, ...detailPages],
  redisListSod
}
